export class ExportManager {
    constructor() {
        this.canvas = document.getElementById('drawing-canvas');
    }

    async exportToSVG(options = {}) {
        const objects = options.objects || [];
        const includeMetadata = options.includeMetadata || false;
        const optimize = options.optimize || false;

        let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${this.canvas.width}" height="${this.canvas.height}">`;
        
        if (includeMetadata) {
            svg += `<!-- Generated by Doppleit Vector v2 Pro -->`;
        }

        objects.forEach(obj => {
            svg += this.objectToSVG(obj);
        });

        svg += `</svg>`;

        if (optimize) {
            svg = this.optimizeSVG(svg);
        }

        return svg;
    }

    async exportToPNG(options = {}) {
        const scale = options.scale || 1;
        const background = options.background || '#ffffff';
        const tempCanvas = document.createElement('canvas');
        tempCanvas.width = this.canvas.width * scale;
        tempCanvas.height = this.canvas.height * scale;
        const ctx = tempCanvas.getContext('2d');

        ctx.fillStyle = background;
        ctx.fillRect(0, 0, tempCanvas.width, tempCanvas.height);

        const objects = options.objects || [];
        objects.forEach(obj => {
            this.drawObjectToCanvas(ctx, obj, scale);
        });

        return tempCanvas.toDataURL('image/png');
    }

    async exportToPDF(options = {}) {
        console.log('PDF export planned for v2');
        return null;
    }

    objectToSVG(obj) {
        let svg = '';
        switch (obj.type) {
            case 'rect':
                svg = `<rect x="${obj.x}" y="${obj.y}" width="${obj.width}" height="${obj.height}" fill="${obj.fill || 'none'}" stroke="${obj.stroke || 'none'}" stroke-width="${obj.strokeWidth || 1}" />`;
                break;
            case 'circle':
                svg = `<circle cx="${obj.cx}" cy="${obj.cy}" r="${obj.r}" fill="${obj.fill || 'none'}" stroke="${obj.stroke || 'none'}" stroke-width="${obj.strokeWidth || 1}" />`;
                break;
            case 'path':
                svg = `<path d="${obj.d}" fill="${obj.fill || 'none'}" stroke="${obj.stroke || 'none'}" stroke-width="${obj.strokeWidth || 1}" />`;
                break;
            case 'text':
                svg = `<text x="${obj.x}" y="${obj.y}" font-size="${obj.fontSize || 16}" fill="${obj.fill || '#000000'}">${obj.content}</text>`;
                break;
            case 'image':
                svg = `<image x="${obj.x}" y="${obj.y}" width="${obj.width}" height="${obj.height}" href="${obj.src}" />`;
                break;
        }
        return svg;
    }

    drawObjectToCanvas(ctx, obj, scale) {
        ctx.save();
        ctx.scale(scale, scale);

        switch (obj.type) {
            case 'rect':
                ctx.fillStyle = obj.fill || 'none';
                ctx.strokeStyle = obj.stroke || 'none';
                ctx.lineWidth = obj.strokeWidth || 1;
                ctx.beginPath();
                ctx.rect(obj.x, obj.y, obj.width, obj.height);
                if (obj.fill) ctx.fill();
                if (obj.stroke) ctx.stroke();
                break;
            case 'circle':
                ctx.fillStyle = obj.fill || 'none';
                ctx.strokeStyle = obj.stroke || 'none';
                ctx.lineWidth = obj.strokeWidth || 1;
                ctx.beginPath();
                ctx.arc(obj.cx, obj.cy, obj.r, 0, Math.PI * 2);
                if (obj.fill) ctx.fill();
                if (obj.stroke) ctx.stroke();
                break;
            case 'path':
                ctx.fillStyle = obj.fill || 'none';
                ctx.strokeStyle = obj.stroke || 'none';
                ctx.lineWidth = obj.strokeWidth || 1;
                const path = new Path2D(obj.d);
                if (obj.fill) ctx.fill(path);
                if (obj.stroke) ctx.stroke(path);
                break;
            case 'text':
                ctx.fillStyle = obj.fill || '#000000';
                ctx.font = `${obj.fontSize || 16}px Inter`;
                ctx.fillText(obj.content, obj.x, obj.y);
                break;
            case 'image':
                const img = new Image();
                img.src = obj.src;
                ctx.drawImage(img, obj.x, obj.y, obj.width, obj.height);
                break;
        }

        ctx.restore();
    }

    optimizeSVG(svg) {
        return svg; // Placeholder for SVG optimization
    }
}